"""Domain models and exceptions for orchestration runs."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Mapping

from providers.base import AgentName
from validation import ValidationReport


@dataclass(frozen=True, slots=True)
class StageResult:
    """Validated result from one agent stage."""

    agent: AgentName
    payload: Mapping[str, Any]
    validation: ValidationReport
    elapsed_seconds: float


@dataclass(frozen=True, slots=True)
class OrchestrationResult:
    """Complete result from one three-stage research run."""

    run_id: str
    question: str
    started_at: datetime
    completed_at: datetime
    stages: tuple[StageResult, ...]

    def payload_for(self, agent: AgentName) -> Mapping[str, Any]:
        """Return the payload generated by one agent."""

        for stage in self.stages:
            if stage.agent == agent:
                return stage.payload
        raise KeyError(f"No stage result for {agent!r}")

    @property
    def final_answer(self) -> str:
        """Return the user-facing answer from the synthesizer output."""

        payload = self.payload_for("synthesizer")
        output = payload.get("output", {})
        if isinstance(output, Mapping):
            plain = output.get("plain_language_answer")
            if isinstance(plain, str) and plain.strip():
                return plain
            direct = output.get("direct_answer")
            if isinstance(direct, str):
                return direct
        return ""


class OrchestrationError(RuntimeError):
    """Base class for controlled orchestration failures."""


class AgentExecutionError(OrchestrationError):
    """Raised when a provider fails before returning an agent payload."""

    def __init__(self, agent: AgentName, message: str) -> None:
        self.agent = agent
        super().__init__(f"{agent} execution failed: {message}")


class AgentValidationError(OrchestrationError):
    """Raised when an agent payload fails structural or semantic validation."""

    def __init__(
        self,
        agent: AgentName,
        report: ValidationReport,
    ) -> None:
        self.agent = agent
        self.report = report
        super().__init__(f"{agent} output failed validation")


class CallBudgetExceeded(OrchestrationError):
    """Raised before a provider call would exceed the configured limit."""
